config/routes.rb
TranslateApp::Application.routes.draw do

  get "feedbacks/vote"

  resources :users
  resources :annotations
  resources :articles

  match '/settings', to: 'users#settings', via: :get
  match '/validate_google_id_token', to: 'users#validate_google_id_token', via: [:get, :post]
  
  
  match '/create_annotation', to: 'annotations#create', via: [:get,:post]
  match '/delete_annotation', to: 'annotations#destroy', via: [:get, :post]
  match '/update_annotation', to: 'annotations#update_translation', via: [:get, :post]
  match '/show_annotation_by_user_url', to: 'annotations#show_by_user_url', via: [:get, :post]
  match '/show_annotation_by_url', to: 'annotations#show_by_url', via: [:get, :post]
  match '/show_annotation_count_by_url', to: 'annotations#show_count_by_url', via: [:get, :post]
  match '/show_user_annotation_history', to: 'annotations#show_user_annotation_history', via: [:get, :post]
  match '/show_user_annotations', to: 'annotations#show_user_annotations', via: [:get, :post]
  match '/show_user_annotated_urls', to: 'annotations#show_user_urls', via: [:get, :post]
  match '/show_most_annotated_urls', to: 'articles#show_most_annotated_urls', via: [:get, :post]

  match '/show_learn_words', to: 'learnings#show_learn_words', via: :post
  match '/view', to: 'learnings#view', via: :post
  match '/take_quiz', to:'learnings#take_quiz', via: :post
  match '/show_user_learning_history', to: 'learnings#show_user_learning_history', via: :post
  match '/show_user_words', to: 'learnings#show_user_words', via: [:get, :post]

  match '/log', to: 'users#log', via: :post

  
  match '/vote', to: 'feedbacks#vote', via: [:get, :post]

  match '/show_learn_words_demo', to: 'demos#show_learn_words', via: :post
  

  match '/create_new_user', to: 'users#create_new_user', via: :get

  match '/sign_up', to: 'users#sign_up_new_user', via: [:get,:post]
  match '/sign_up_complete', to: 'users#sign_up_complete', via: :get

  match '/login', to: 'sessions#new', via: :get
  match '/login', to: 'sessions#create', via: :post
  match '/login_complete', to: 'sessions#login_complete', via: :get
  match '/logout', to: 'sessions#logout', via: :get
  match '/request_password_reset', to: 'PasswordResets#request_password_reset', via: [:get,:post]
  match '/password_reset/:id', to: 'PasswordResets#reset_password', via: [:get,:post]

  match '/auth/:provider/callback', to: 'sessions#authenticate_social', via: :get
  match '/auth/failure', to: 'sessions#authenticate_social_failure', via: [:get, :post]

  match '/auth/facebook/most_annotate_share', to: 'facebook#share_most_annotated', via: :post
  match '/auth/facebook/post_recommend', to: 'facebook#post_recommend', via: :post

end

app/controllers/password_resets_controller.rb
require 'bcrypt'

class PasswordResetsController < ApplicationController
  # before_action :get_user,   only: [:reset_password]
  # before_action :valid_user, only: [:reset_password]
  # before_action :check_expiration, only: [:reset_password]

  def request_password_reset
    if request.post?
      @user = User.where(email: params[:password_reset][:email].downcase).first
      if @user
        @user.create_reset_digest
        @user.send_password_reset_email
        flash[:info] = "Email sent with password reset instructions"
        redirect_to "/login"
      else
        flash.now[:error] = "Email address not found"
        render 'request_password_reset'
      end
    else
      render 'request_password_reset'
    end
  end

  def reset_password

    # Email test
    if !ValidationHandler.validate_email(params[:email])
      flash[:error] = Utilities::Message::MSG_INVALID_EMAIL
      Rails.logger.debug "reset_password: Invalid email"
      redirect_to "/login"
      return
    end

    # Test email length
    if params[:email].to_s.length > USER_EMAIL_MAX_LENGTH
      flash[:error] = Utilities::Message::MSG_EMAIL_MAX_LENGTH
      Rails.logger.debug "reset_password: Max Length reached"
      redirect_to "/login"
      return
    end

    # store email as lowercase!!!!!!!!!!!
    input_email = params[:email].to_s.downcase

    # Test unique email. Use lowercased email!!!
    @user = User.where(:email => input_email).first
    if @user.nil?
      flash[:error] = Utilities::Message::MSG_INVALID_EMAIL
      Rails.logger.debug "reset_password: Email not found"
      redirect_to "/login"
      return
    end

    unless (@user && @user.authenticated?(:reset, params[:id]))
      flash[:error] = Utilities::Message::MSG_INVALID_EMAIL
      Rails.logger.debug "reset_password: Reset not authenticated User[ " + @user.public_key.to_s + "] reset_token= " + params[:id]
      redirect_to "/login"
      return
    end

    if @user.password_reset_expired?
      Rails.logger.debug "reset_password: Reset expired User[ " + @user.public_key.to_s + "]"
      flash[:error] = "Password reset has expired."
      redirect_to "/login"
      return
    end

    if request.post?
      if params[:user][:password].empty? || params[:user][:password_confirmation].empty?
        Rails.logger.debug "reset_password Post: Password empty User[ " + @user.public_key.to_s + "]"
        flash[:error] = "Passwords can't be empty"
        redirect_to :controller => "PasswordResets", :action => "reset_password", :id => params[:id], :email => params[:email]
        return
      end

      if params[:user][:password] != params[:user][:password_confirmation]
        Rails.logger.debug "reset_password Post: Password not same User[ " + @user.public_key.to_s + "]"
        flash[:error] = "Passwords are not the same"
        redirect_to :controller => "PasswordResets", :action => "reset_password", :id => params[:id], :email => params[:email]
        return
      end

      @user.password_digest = BCrypt::Password.create(params[:user][:password])

      if !@user.save
        Rails.logger.debug "reset_password Post: User[" + @user.public_key.to_s + "] Error saving"
        flash[:error] = Utilities::Message::MSG_GENERAL_FAILURE
        redirect_to :controller => "PasswordResets", :action => "reset_password", :id => params[:id], :email => params[:email]
        return
      end

      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:info] = "Password has been reset."
      redirect_to "/login"

    end
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/request_password_reset.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: request_password_reset_path) do |f| %>
        <% if flash[:error] || flash[:errors] %>
            <div class="alert alert-danger"><%= flash[:error] || flash[:errors] %></div>
        <% end %>
        <% if flash[:info] %>
            <div class="alert alert-info"><%= flash[:info] || flash[:info] %></div>
        <% end %>
        <% flash[:error] = flash[:errors] = flash[:info] = nil %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/reset_password.html.erb
<% provide(:title, 'WordNews - Reset password') %>
<h1>WordNews - Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url:{:controller => "PasswordResets", :action => "reset_password", :id => params[:id]},
                 method: :post, :html => { :id => "reset_password", :class => "reset_password" } ) do |f| %>

        <% if flash[:error] || flash[:errors] %>
            <div class="alert alert-danger"><%= flash[:error] || flash[:errors] %></div>
        <% end %>
        <% if flash[:info] %>
            <div class="alert alert-info"><%= flash[:info] || flash[:info] %></div>
        <% end %>
        <% flash[:error] = flash[:errors] = flash[:info] = nil %>

        <%= hidden_field_tag :email, @user.email %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control'%>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control'%>

        <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>