config/routes.rb
TranslateApp::Application.routes.draw do

  get "feedbacks/vote"

  resources :users
  resources :annotations
  resources :articles

  match '/settings', to: 'users#settings', via: :get
  match '/validate_google_id_token', to: 'users#validate_google_id_token', via: [:get, :post]
  
  
  match '/create_annotation', to: 'annotations#create', via: [:get,:post]
  match '/delete_annotation', to: 'annotations#destroy', via: [:get, :post]
  match '/update_annotation', to: 'annotations#update_translation', via: [:get, :post]
  match '/show_annotation_by_user_url', to: 'annotations#show_by_user_url', via: [:get, :post]
  match '/show_annotation_by_url', to: 'annotations#show_by_url', via: [:get, :post]
  match '/show_annotation_count_by_url', to: 'annotations#show_count_by_url', via: [:get, :post]
  match '/show_user_annotation_history', to: 'annotations#show_user_annotation_history', via: [:get, :post]
  match '/show_user_annotations', to: 'annotations#show_user_annotations', via: [:get, :post]
  match '/show_user_annotated_urls', to: 'annotations#show_user_urls', via: [:get, :post]
  match '/show_most_annotated_urls', to: 'articles#show_most_annotated_urls', via: [:get, :post]

  match '/show_learn_words', to: 'learnings#show_learn_words', via: :post
  match '/view', to: 'learnings#view', via: :post
  match '/take_quiz', to:'learnings#take_quiz', via: :post
  match '/show_user_learning_history', to: 'learnings#show_user_learning_history', via: :post
  match '/show_user_words', to: 'learnings#show_user_words', via: [:get, :post]

  match '/log', to: 'users#log', via: :post

  
  match '/vote', to: 'feedbacks#vote', via: [:get, :post]

  match '/show_learn_words_demo', to: 'demos#show_learn_words', via: :post
  

  match '/create_new_user', to: 'users#create_new_user', via: :get

  match '/sign_up', to: 'users#sign_up_new_user', via: [:get,:post]
  match '/sign_up_complete', to: 'users#sign_up_complete', via: :get

  match '/login', to: 'sessions#new', via: :get
  match '/login', to: 'sessions#create', via: :post
  match '/login_complete', to: 'sessions#login_complete', via: :get
  match '/logout', to: 'sessions#logout', via: :get
  match '/request_password_reset', to: 'PasswordResets#request_password_reset', via: [:get,:post]
  match '/password_reset/:id', to: 'PasswordResets#reset_password', via: [:get,:post]

  match '/auth/:provider/callback', to: 'sessions#authenticate_social', via: :get
  match '/auth/failure', to: 'sessions#authenticate_social_failure', via: [:get, :post]

  match '/auth/facebook/most_annotate_share', to: 'facebook#share_most_annotated', via: :post
  match '/auth/facebook/post_recommend', to: 'facebook#post_recommend', via: :post

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :annotation_count, :lang, :url, :url_postfix, :website, :title, :publication_date
  has_many :annotations
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require 'date'
  
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
  
  
  # from_date and to_date are optional (both provided or both omitted)
  # TODO: html shows error msg properly
  def show_most_annotated_urls
    if !params[:lang].present?  or !params[:num].present?  \
        or !ValidationHandler.validate_integer(params[:num]) \
        or params[:from_date].present?^params[:to_date].present?
        
      respond_to do |format|
        format.html { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
        format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
      end
    return
    end
    @lang = params[:lang]
    @num = params[:num]
    
    if params[:user_id].present?
      @user_id = params[:user_id]
    end
    
    if params[:from_date].present? and params[:to_date].present? 
      @from_date = params[:from_date]
      @to_date = params[:to_date]
    
      if !ValidationHandler.validate_date(@from_date) or !ValidationHandler.validate_date(@to_date)
        respond_to do |format|
          format.html { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
          format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
        end
        return
      end
      
      @articles = Article.where("lang=? and publication_date>=? and publication_date<=? and annotation_count>1", 
      @lang, @from_date, @to_date).order('annotation_count desc').limit(@num)
        
      @time_msg = 'from ' + @from_date + ' to ' + @to_date
    else
      @articles = Article.where('lang=? and  annotation_count>1 ', @lang).order('annotation_count desc').limit(@num)
      @time_msg = 'all the time'
    end
    
    @articles.each do |article|
      article.lang = Utilities::Lang::CODE_TO_LANG[article.lang.to_sym]
    end

    if params[:user_id].present?
      @user_id = params[:user_id]
    end

    respond_to do |format|
      format.html # show_most_annotated_urls.html.erb
      format.json { render json: {msg: Utilities::Message::MSG_OK, urls: @articles}, 
                  status: :ok}
    end
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :url_postfix %><br />
    <%= f.text_field :url_postfix %>
  </div>
  <div class="field">
    <%= f.label :annotation_count %><br />
    <%= f.text_field :annotation_count %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :lang %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table class="table table-striped">
  <tr>
    <th>Website</th>
    <th>Url</th>
    <th>Url postfix</th>
    <th>Annotation count</th>
    <th>Language</th>
    <th>Publication Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.website %></td>
    <td><%= article.url %></td>
    <td><%= article.url_postfix %></td>
    <td><%= article.annotation_count %></td>
    <td><%= article.lang %></td>
    <td><%= article.publication_date %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Website:</b>
  <%= @article.website %>
</p>

<p>
  <b>Url:</b>
  <%= @article.url %>
</p>

<p>
  <b>Url postfix:</b>
  <%= @article.url_postfix %>
</p>

<p>
  <b>Annotation count:</b>
  <%= @article.annotation_count %>
</p>

<p>
  <b>Language:</b>
  <%= @article.lang %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/show_most_annotated_urls.html.erb
<h1>Most annotated articles <%= @time_msg %> </h1>

<div class="text-center" style="min-height: 40px">
  <% if @user_id %>
      <a href="<%= facebook_most_annotated_share_path(@lang, @num, @from_date, @to_date, @user_id) %>" 
         class="btn-sm btn-social btn-facebook btn-flat" data-lang="<%= @lang %>" 
         data-num="<%= @num %>" data-from-date="<%= @from_date %>" 
         data-to-date="<%= @to_date %>" data-user-id="<%= @user_id %>" id="fb-anno-share">
        <i class="fa fa-facebook"></i>
        Share
      </a>
  <% else %>
      <a href="<%= facebook_most_annotated_share_path(@lang, @num, @from_date, @to_date) %>" 
         class="btn-sm btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i>
        Share
      </a>
  <% end %>
  
</div>

<div>
  <table class="table table-striped">
    <tr>
      <td>No.</td>
      <th>Article</th>
      <th>Annotation count</th>
      <th>Language</th>
      <th>Publication Date</th>
    </tr>
  <% @articles.each_with_index do |article, index| %>
    <tr>
      <td><%=index+1 %></td>
      <td><a href='<%=article.url %>'><%= article.title %></a></td>
      <td><%= article.annotation_count %></td>
      <td><%= article.lang %></td>
      <td><%= article.publication_date %></td>
    </tr>
  <% end %>
  </table>
</div>
<br />