config/routes.rb
TranslateApp::Application.routes.draw do

  get "feedbacks/vote"

  resources :users
  resources :annotations
  resources :articles

  match '/settings', to: 'users#settings', via: :get
  match '/validate_google_id_token', to: 'users#validate_google_id_token', via: [:get, :post]
  
  
  match '/create_annotation', to: 'annotations#create', via: [:get,:post]
  match '/delete_annotation', to: 'annotations#destroy', via: [:get, :post]
  match '/update_annotation', to: 'annotations#update_translation', via: [:get, :post]
  match '/show_annotation_by_user_url', to: 'annotations#show_by_user_url', via: [:get, :post]
  match '/show_annotation_by_url', to: 'annotations#show_by_url', via: [:get, :post]
  match '/show_annotation_count_by_url', to: 'annotations#show_count_by_url', via: [:get, :post]
  match '/show_user_annotation_history', to: 'annotations#show_user_annotation_history', via: [:get, :post]
  match '/show_user_annotations', to: 'annotations#show_user_annotations', via: [:get, :post]
  match '/show_user_annotated_urls', to: 'annotations#show_user_urls', via: [:get, :post]
  match '/show_most_annotated_urls', to: 'articles#show_most_annotated_urls', via: [:get, :post]

  match '/show_learn_words', to: 'learnings#show_learn_words', via: :post
  match '/view', to: 'learnings#view', via: :post
  match '/take_quiz', to:'learnings#take_quiz', via: :post
  match '/show_user_learning_history', to: 'learnings#show_user_learning_history', via: :post
  match '/show_user_words', to: 'learnings#show_user_words', via: [:get, :post]

  match '/log', to: 'users#log', via: :post

  
  match '/vote', to: 'feedbacks#vote', via: [:get, :post]

  match '/show_learn_words_demo', to: 'demos#show_learn_words', via: :post
  

  match '/create_new_user', to: 'users#create_new_user', via: :get

  match '/sign_up', to: 'users#sign_up_new_user', via: [:get,:post]
  match '/sign_up_complete', to: 'users#sign_up_complete', via: :get

  match '/login', to: 'sessions#new', via: :get
  match '/login', to: 'sessions#create', via: :post
  match '/login_complete', to: 'sessions#login_complete', via: :get
  match '/logout', to: 'sessions#logout', via: :get
  match '/request_password_reset', to: 'PasswordResets#request_password_reset', via: [:get,:post]
  match '/password_reset/:id', to: 'PasswordResets#reset_password', via: [:get,:post]

  match '/auth/:provider/callback', to: 'sessions#authenticate_social', via: :get
  match '/auth/failure', to: 'sessions#authenticate_social_failure', via: [:get, :post]

  match '/auth/facebook/most_annotate_share', to: 'facebook#share_most_annotated', via: :post
  match '/auth/facebook/post_recommend', to: 'facebook#post_recommend', via: :post

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :reset_token

  attr_accessible :user_name, :email, :avatar, :status, 
                  :password_digest, :public_key,
                  :role, :score, :rank,
                  :view_count, :quiz_count, :learning_count, :learnt_count, 
                  :annotation_count, :vote_count, :facebook_share_count
  validates :user_name, length: { maximum: 255 }

  validates :email, length: { maximum: 255 }
  validates :public_key, uniqueness: true
  has_many :histories, :dependent => :destroy

  # Returns the hash digest of the given string.
  def self.digest(string)
    BCrypt::Password.create(string)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
      digest = send("#{attribute}_digest")
      return false if digest.nil?
      BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
  #include UserHandler
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    #@user = User.where(:user_name => @user_name).first
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end


  # not implemented yet
  def settings
    public_key = params[:user_id]
    @user = nil
    @msg = Utilities::Message::MSG_GENERAL_FAILURE
    # Validate userID
    if !UserHandler.validate_public_key( public_key )
      @msg = Utilities::Message::MSG_INVALID_PARA
      return render status: :bad_request
    end

    @user = User.where(:public_key => public_key).first
    if @user.nil?
      Rails.logger.warn "settings: User[" + public_key.to_s + "] not found"
      @msg = Utilities::Message::MSG_SHOW_USER_NOT_FOUND
      return render status: :bad_request
    end

    respond_to do |format|
      format.html #  settings.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end



  # TODO think about deprecating this.
  def log
    result = Hash.new

    if !params[:user_id].present? or !params[:time_elapsed].present? or\
       !params[:activity].present?
       result['mgs'] = Utilities::Message::MSG_INVALID_PARA
      return render json: result, status: :bad_request
    end
    
    public_key = params[:user_id]
    
    # Validate userID
    if !UserHandler.validate_public_key( public_key )
      result['msg'] = Utilities::Message::MSG_INVALID_PARA
      return render json: result, status: :bad_request
    end

    @user = User.where(:public_key => public_key).first
    if @user.nil?
      Rails.logger.warn "settings: User[" + public_key.to_s + "] not found"
      result['msg'] = Utilities::Message::MSG_SHOW_USER_NOT_FOUND
      return render json: result, status: :bad_request
    end

    if params[:detail].present?
      USER_ACTION_LOGGER.info( "Log: User[" + public_key.to_s + "], Elasped_t:" + params[:time_elapsed].to_s + ", Action:" + params[:activity].to_s + ", Detail: " + params[:detail].to_s)
    else
      USER_ACTION_LOGGER.info( "Log: User[" + public_key.to_s + "], Elasped_t:" + params[:time_elapsed].to_s + ", Action:" + params[:activity].to_s)
    end

    result['msg'] = Utilities::Message::MSG_OK
    return render json: result
  end
  

  def validate_google_id_token
    email = Utilities::UserHandler::email_if_google_id_valid(params[:id_token])
    if email.blank?
      logger.info('No valid identity token present')
      render status: 401, nothing: true
    else
	  result = Hash.new
	  result['email'] = email
      render status: 200, json: result
    end
  end



  def create_new_user
    result = Hash.new
    result['msg'] = Utilities::Message::MSG_GENERAL_FAILURE

    user = UserHandler.create_new_user()
    if !user.nil?
      result['user'] = Hash.new
      result['user']['user_id'] = user.public_key.to_i
      result['user']['rank'] = user.rank
      result['user']['score'] = user.score
      result['msg'] =  Utilities::Message::MSG_OK
    else
      result['msg'] =  Utilities::Message::MSG_CREATE_FAILURE
      return render json: result, status: :internal_server_error
    end

    render json: result
  end

  def sign_up_new_user
    if request.get?
      public_key = params[:user_id]

      @user = User.new()
      if !UserHandler.validate_public_key( public_key )
        flash[:error] = Utilities::Message::MSG_INVALID_PARA
        return
      end

      user_check = User.where(:public_key => public_key).first
      if user_check.nil?
        Rails.logger.warn "sign_up_new_user: User[" + public_key.to_s + "] not found"
        flash[:error] = Utilities::Message::MSG_SHOW_USER_NOT_FOUND
        return
      end

      @user.public_key = public_key
      @pub_key = public_key
    else
      user_param = params[:user]
      public_key = user_param[:public_key]

      @user = User.new()
      if !UserHandler.validate_public_key( public_key )
        flash[:error] = Utilities::Message::MSG_INVALID_PARA
        redirect_to :action => "sign_up_new_user", :user_id => public_key
        return
      end

      user_check = User.where(:public_key => public_key).first
      if user_check.nil?
        Rails.logger.debug "sign_up_new_user Post: User[" + public_key.to_s + "] not found"
        flash[:error] = Utilities::Message::MSG_SHOW_USER_NOT_FOUND
        redirect_to :action => "sign_up_new_user", :user_id => public_key
        return
      end

      if ( !user_param[:user_name].present? || !user_param[:email].present? \
          || !user_param[:password].present? || !user_param[:password_confirmation].present? )
        Rails.logger.debug "sign_up_new_user Post: User[" + public_key.to_s + "] missing parameters"
        flash[:error] = Utilities::Message::MSG_MISSING_SIGN_UP_PARAMS
        redirect_to :action => "sign_up_new_user", :user_id => public_key
        return
      end

      # Test user_name length
      if user_param[:user_name].to_s.length > USER_NAME_MAX_LENGTH
        Rails.logger.debug "sign_up_new_user Post: User[" + public_key.to_s + "] Name;[" + user_param[:user_name].to_s + "] exceed name length"
        flash[:error] = Utilities::Message::MSG_USER_NAME_MAX_LENGTH
        redirect_to :action => "sign_up_new_user", :user_id => public_key
        return
      end

      # Email test
      if !ValidationHandler.validate_email(user_param[:email])
        Rails.logger.debug "sign_up_new_user Post: User[" + public_key.to_s + "] Email:[" + user_param[:email].to_s + "] Invalid"
        flash[:error] = Utilities::Message::MSG_INVALID_EMAIL
        redirect_to :action => "sign_up_new_user", :user_id => public_key
        return
      end

      # Test email length
      if user_param[:email].to_s.length > USER_EMAIL_MAX_LENGTH
        Rails.logger.debug "sign_up_new_user Post: User[" + public_key.to_s + "] Email:[" + user_param[:email].to_s + "] exceed max length"
        flash[:error] = Utilities::Message::MSG_EMAIL_MAX_LENGTH
        redirect_to :action => "sign_up_new_user", :user_id => public_key
        return
      end

      # store email as lowercase!!!!!!!!!!!
      input_email = user_param[:email].to_s.downcase

      # Test unique email. Use lowercased email!!!
      user_email_test = User.where(:email => input_email).first
      if !user_email_test.nil?
        Rails.logger.debug "sign_up_new_user Post: User[" + public_key.to_s + "] Email:[" + user_param[:email].to_s + "] already registered"
        flash[:error] = Utilities::Message::MSG_EMAIL_DUPLICATE
        redirect_to :action => "sign_up_new_user", :user_id => public_key
        return
      end

      # Test if password and password_confirmation is same
      if user_param[:password] != user_param[:password_confirmation]
        Rails.logger.debug "sign_up_new_user Post: User[" + public_key.to_s + "] Password is not same"
        flash[:error] = Utilities::Message::MSG_PASSWORD_IS_NOT_SAME
        redirect_to :action => "sign_up_new_user", :user_id => public_key
        return
      end

      user_check.user_name = user_param[:user_name].to_s
      user_check.email = input_email
      user_check.password_digest = BCrypt::Password.create(user_param[:password])
      user_check.registered_at = Time.now()

      if !user_check.save
        Rails.logger.debug "sign_up_new_user Post: User[" + public_key.to_s + "] Error saving"
        flash[:error] = Utilities::Message::MSG_GENERAL_FAILURE
        redirect_to :action => "sign_up_new_user", :user_id => public_key
        return
      end

      log_in user_check
      redirect_to :action => "sign_up_complete"
    end
  end

  def sign_up_complete
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>User</th>
    <th>User name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.user_name %></td>
    <td><%= link_to 'Show', user %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/settings.html.erb
<% if @user.nil? %>
    <ul class="nav">
      <%= @msg %>
    </ul>
<% else %>
<ul >
	<li>User Name: <%=  @user.user_name %></li>
</ul>


<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user.id %>
</p>

<p>
  <b>User name:</b>
  <%= @user.user_name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/sign_up_complete.erb
<% provide(:title, 'Sign Up Complete') %>
<h1>Sign up done!</h1>
<h2>Thank you!</h2>

<h2>Please go ahead and <%= link_to "login", :action => "new", :controller => "sessions" %></h2>

app/views/users/sign_up_new_user.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: "/sign_up", method: :post do |f| %>
        <% if flash[:error] || flash[:errors] %>
            <div class="alert alert-danger"><%= flash[:error] || flash[:errors] %></div>
        <% end %>
        <% if flash[:info] %>
            <div class="alert alert-info"><%= flash[:info] || flash[:info] %></div>
        <% end %>
        <% flash[:error] = flash[:errors] = flash[:info] = nil %>

        <%= f.hidden_field :public_key %>
        <%= f.label :user_name, "User Name" %>
        <%= f.text_field :user_name, class: 'form-control', :required => true%>

        <%= f.label :email, "Email Address" %>
        <%= f.email_field :email, class: 'form-control', :required => true%>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', :required => true%>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, class: 'form-control', :required => true%>

        <%= f.submit "Sign Up!", class: "btn btn-primary" %>
    <% end %>
    <div class="text-center">
      <p style="text-align: center"> - OR - </p>
      <a href="<%= social_auth_path(:facebook, "signup", @pub_key) %>" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i>
        Sign up with Facebook
      </a>
    </div>
  </div>
</div>