config/routes.rb
TranslateApp::Application.routes.draw do

  get "feedbacks/vote"

  resources :users
  resources :annotations
  resources :articles

  match '/settings', to: 'users#settings', via: :get
  match '/validate_google_id_token', to: 'users#validate_google_id_token', via: [:get, :post]
  
  
  match '/create_annotation', to: 'annotations#create', via: [:get,:post]
  match '/delete_annotation', to: 'annotations#destroy', via: [:get, :post]
  match '/update_annotation', to: 'annotations#update_translation', via: [:get, :post]
  match '/show_annotation_by_user_url', to: 'annotations#show_by_user_url', via: [:get, :post]
  match '/show_annotation_by_url', to: 'annotations#show_by_url', via: [:get, :post]
  match '/show_annotation_count_by_url', to: 'annotations#show_count_by_url', via: [:get, :post]
  match '/show_user_annotation_history', to: 'annotations#show_user_annotation_history', via: [:get, :post]
  match '/show_user_annotations', to: 'annotations#show_user_annotations', via: [:get, :post]
  match '/show_user_annotated_urls', to: 'annotations#show_user_urls', via: [:get, :post]
  match '/show_most_annotated_urls', to: 'articles#show_most_annotated_urls', via: [:get, :post]

  match '/show_learn_words', to: 'learnings#show_learn_words', via: :post
  match '/view', to: 'learnings#view', via: :post
  match '/take_quiz', to:'learnings#take_quiz', via: :post
  match '/show_user_learning_history', to: 'learnings#show_user_learning_history', via: :post
  match '/show_user_words', to: 'learnings#show_user_words', via: [:get, :post]

  match '/log', to: 'users#log', via: :post

  
  match '/vote', to: 'feedbacks#vote', via: [:get, :post]

  match '/show_learn_words_demo', to: 'demos#show_learn_words', via: :post
  

  match '/create_new_user', to: 'users#create_new_user', via: :get

  match '/sign_up', to: 'users#sign_up_new_user', via: [:get,:post]
  match '/sign_up_complete', to: 'users#sign_up_complete', via: :get

  match '/login', to: 'sessions#new', via: :get
  match '/login', to: 'sessions#create', via: :post
  match '/login_complete', to: 'sessions#login_complete', via: :get
  match '/logout', to: 'sessions#logout', via: :get
  match '/request_password_reset', to: 'PasswordResets#request_password_reset', via: [:get,:post]
  match '/password_reset/:id', to: 'PasswordResets#reset_password', via: [:get,:post]

  match '/auth/:provider/callback', to: 'sessions#authenticate_social', via: :get
  match '/auth/failure', to: 'sessions#authenticate_social_failure', via: [:get, :post]

  match '/auth/facebook/most_annotate_share', to: 'facebook#share_most_annotated', via: :post
  match '/auth/facebook/post_recommend', to: 'facebook#post_recommend', via: :post

end

app/models/annotation.rb
# TODO: remove columns
class Annotation < ActiveRecord::Base
  attr_accessible :lang, :paragraph_idx, :selected_text, :text_idx, :translation, :article_id, :article, :vote, :implicit_vote
  belongs_to :article
  has_many :annotation_histories
end

app/controllers/annotations_controller.rb
#require 'message_code.rb'

class AnnotationsController < ApplicationController
  
  # GET /annotations
  # GET /annotations.json
  def index
    @annotations = Annotation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @annotations }
    end
  end

  # GET /annotations/1
  # GET /annotations/1.json
  def show
    @annotation = Annotation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @annotation }
    end
  end
  
  
  # Return the annotatations done by a given user for a given URL
  def show_by_user_url
    if !params[:user_id].present? or !params[:url_postfix].present? or !params[:lang].present?
      respond_to do |format|
        format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
      end
      return
    end

    user = User.where(:public_key => params[:user_id]).first
    if user.nil?
      # response
      respond_to do |format|
        format.json { render json: { msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request }
      end
      return 
    end
    user_id = user.id

    article_id = Utilities::ArticleUtil.get_article_id(params[:url_postfix], params[:lang])
    
    @annotations = article_id.nil? ? {}: Annotation.joins(:annotation_histories).where('annotation_histories.user_id=? AND article_id=?', user_id, article_id)
     
    respond_to do |format|
      format.json { render json: {msg: Utilities::Message::MSG_OK, annotations: @annotations}, 
                    status: :ok}
    end
  end
  
  
  # Return the annotations for a given URL
  def show_by_url
    if !params[:url_postfix].present? or !params[:lang].present?
      respond_to do |format|
        format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
      end
      return
    end
    
    article_id = Utilities::ArticleUtil.get_article_id(params[:url_postfix], params[:lang])
    @annotations = article_id.nil? ? {} : Annotation.where('article_id=?', article_id)
    
    respond_to do |format|
      format.json { render json: {msg: Utilities::Message::MSG_OK, annotations: @annotations}, 
                    status: :ok}
    end
  end
  
  
  # Return the number of annotations for a given URL
  def show_count_by_url
    if !params[:url_postfix].present? or !params[:lang].present?
      respond_to do |format|
        format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
      end
      return
    end
    
    count = Article.where('url_postfix=? AND lang=?', params[:url_postfix], params[:lang]).pluck(:annotation_count).first
    
    respond_to do |format|
      format.json { render json: {msg: Utilities::Message::MSG_OK, 
                    annotation_count: count}, status: :ok}      
    end
  end
  
  
  # TODO: 1. Move to users_controller.rb? 2. Add two columns in user table
  # lang is optional
  def show_user_annotation_history
    
    if !params[:user_id].present?
      respond_to do |format|
        format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
      end
      return
    end

    user = User.where(:public_key => params[:user_id]).first
    if user.nil?
      # response
      respond_to do |format|
        format.json { render json: { msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request }
      end
      return 
    end
    user_id = user.id

    if params[:lang].present?
      total_annotation = AnnotationHistory.where(user_id: user_id, lang: params[:lang]).count('id')
      total_url = AnnotationHistory.where(user_id: user_id, lang: params[:lang]).joins(:annotation).count('article_id', distinct: true)
    else
      total_annotation = AnnotationHistory.where(user_id: user_id).count('id')
      total_url = AnnotationHistory.where(user_id: user_id).joins(:annotation).count('article_id', distinct: true)
    end
    
    respond_to do |format|
      format.json { render json: {msg: Utilities::Message::MSG_OK, 
                    history: {annotation: total_annotation, url: total_url}},
                    status: :ok}
    end
   
  end
  
  # All the annotations done by a user
  # lang is optional
  def show_user_annotations    
    if !params[:user_id].present?
      respond_to do |format|
        format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
      end
      return
    end

    # invalid ID
    @user = User.where(:public_key => params[:user_id]).first
    if @user.nil?
      respond_to do |format|
        format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
      end
      return
    end
      
    if params[:lang].present?
      @annotations = Annotation.where('annotations.lang=?', params[:lang]).joins(:annotation_histories).where('user_id=?', @user.id)
      lang = Utilities::Lang::CODE_TO_LANG[params[:lang].to_sym]
      @annotations.each do |annotation|
        annotation.lang = lang
      end
    else
      @annotations = Annotation.joins(:annotation_histories).where('user_id=?', @user.id)
      @annotations.each do |annotation|
        annotation.lang = Utilities::Lang::CODE_TO_LANG[annotation.lang.to_sym]
      end
    end

    respond_to do |format|
      format.html # show_user_annotations.html.erb
      format.json { render json: {msg: Utilities::Message::MSG_OK, annotations: @annotations}, 
                    status: :ok}
    end
  end
  
  
  # All the annotated urls done by a user
  # lang is optional
  def show_user_urls
    if !params[:user_id].present?
       respond_to do |format|
        format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
      end
      return
    end

    @user = User.where(:public_key => params[:user_id]).first
    if @user.nil?
      respond_to do |format|
        format.json { render json: {msg: Utilities::Message::MSG_INVALID_PARA}, 
                      status: :bad_request}
      end
      return
    end
    
    if params[:lang].present?
      article_ids = Annotation.joins(:annotation_histories).where('user_id=? and annotation_histories.lang=?', @user.id, params[:lang]).pluck(:article_id).uniq
    else
      article_ids = Annotation.joins(:annotation_histories).where('user_id=?', @user.id).pluck(:article_id).uniq
    end
    
    @articles = Article.where(id: article_ids)
    @articles.each do |article|
      article.lang = Utilities::Lang::CODE_TO_LANG[article.lang.to_sym]
    end

    respond_to do |format|
      format.html # show_user_annotations.html.erb
      format.json { render json: {msg: Utilities::Message::MSG_OK, articles: @articles}, status: :ok}
    end
  end
  


  # GET /annotations/new
  # GET /annotations/new.json
  def new
    @annotation = Annotation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @annotation }
    end
  end

  # GET /annotations/1/edit
  def edit
    @annotation = Annotation.find(params[:id])
  end


  # POST /annotations
  # POST /annotations.json
  def create
    
    # TODO: a better validation strategy (use strong parameter?)
    if (!params[:annotation].present? or !params[:annotation][:ann_id].present? \
        or !params[:annotation][:user_id].present? \
        or !params[:annotation][:selected_text].present? \
        or !params[:annotation][:translation].present? \
        or !params[:annotation][:lang].present?\
        or !params[:annotation][:paragraph_idx].present?\
        or !params[:annotation][:text_idx].present?\
        or !params[:annotation][:url].present? \
        or !params[:annotation][:url_postfix].present? \
        or !params[:annotation][:website].present?)
        
      respond_to do |format|
        format.json { render json: { msg: Utilities::Message::MSG_INVALID_PARA }, 
                      status: :bad_request } 
      end
      return
    end

    user = User.where(:public_key => params[:annotation][:user_id]).first
    
    if !Utilities::UserLevel.validate(user.rank, user.registered_at, :annotate_news_sites)
      respond_to do |format|
        format.json { render json: { msg: Utilities::Message::MSG_INSUFFICIENT_RANK}, 
                       status: :bad_request }
      end
      return 
    end

    # Obtain article or create if not exists
    article = Utilities::ArticleUtil.get_or_create_article(
      params[:annotation][:url], params[:annotation][:url_postfix],
      params[:annotation][:lang], params[:annotation][:website], 
      params[:annotation][:title], params[:annotation][:publication_date])
      
    @annotation = Annotation.where(
      selected_text: params[:annotation][:selected_text],
      translation: params[:annotation][:translation],
      lang: params[:annotation][:lang],
      paragraph_idx: params[:annotation][:paragraph_idx],
      text_idx: params[:annotation][:text_idx],
      article_id: article.id).first
      
    # TODO: consider to increase upvote when annotation exists
    if @annotaion.nil?
      @annotation = Annotation.new(
      selected_text: params[:annotation][:selected_text],
      translation: params[:annotation][:translation],
      lang: params[:annotation][:lang],
      paragraph_idx: params[:annotation][:paragraph_idx],
      text_idx: params[:annotation][:text_idx],
      article_id: article.id)
    end
    
    @annotation_history = AnnotationHistory.new(
      client_ann_id: params[:annotation][:ann_id], 
      user_id: user.id,
      lang: params[:annotation][:lang])
    
    success = true
    Annotation.transaction do
      if @annotation.new_record?
        success &&= @annotation.save
        # store the text and its pronunciation if it is a new word 

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/views/annotations/_form.html.erb
<%= form_for(@annotation) do |f| %>
  <% if @annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>

      <ul>
      <% @annotation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :ann_id %><br />
    <%= f.number_field :ann_id %>
  </div>
  <div class="field">
    <%= f.label :selected_text %><br />
    <%= f.text_field :selected_text %>
  </div>
  <div class="field">
    <%= f.label :translation %><br />
    <%= f.text_field :translation %>
  </div>
  <div class="field">
    <%= f.label :lang %><br />
    <%= f.text_field :lang %>
  </div>
  <div class="field">
    <%= f.label :paragraph_idx %><br />
    <%= f.number_field :paragraph_idx %>
  </div>
  <div class="field">
    <%= f.label :text_idx %><br />
    <%= f.number_field :text_idx %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/annotations/edit.html.erb
<h1>Editing annotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @annotation %> |
<%= link_to 'Back', annotations_path %>

app/views/annotations/index.html.erb
<h1>Listing annotations</h1>

<table class="table table-striped">
  <tr>
    <th>Internal ID</th>
    <th>Selected text</th>
    <th>Translation</th>
    <th>Language</th>
    <th>Paragraph idx</th>
    <th>Text idx</th>
    <th>Article ID</th>
    <th>Article URL</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @annotations.each do |annotation| %>
  <tr>
    <td><%= annotation.id %></td>
    <td><%= annotation.selected_text %></td>
    <td><%= annotation.translation %></td>
    <td><%= annotation.lang %></td>
    <td><%= annotation.paragraph_idx %></td>
    <td><%= annotation.text_idx %></td>
    <td><%= annotation.article_id%></td>
    <td><%= annotation.article.nil? ? '': annotation.article.url%></td>
    <td><%= link_to 'Show', annotation %></td>
    <td><%= link_to 'Edit', edit_annotation_path(annotation) %></td>
    <td><%= link_to 'Destroy', annotation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Annotation', new_annotation_path %>

app/views/annotations/new.html.erb
<h1>New annotation</h1>

<%= render 'form' %>

<%= link_to 'Back', annotations_path %>

app/views/annotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Internal ID:</b>
    <%= @annotation.id %>
</p>

<p>
  <b>Selected text:</b>
  <%= @annotation.selected_text %>
</p>

<p>
  <b>Translation:</b>
  <%= @annotation.translation %>
</p>

<p>
  <b>Language:</b>
  <%= @annotation.lang %>
</p>

<p>
  <b>Paragraph idx:</b>
  <%= @annotation.paragraph_idx %>
</p>

<p>
  <b>Text idx:</b>
  <%= @annotation.text_idx %>
</p>

<p>
  <b>Url:</b>
  <%= @annotation.article.url %>
</p>


<%= link_to 'Edit', edit_annotation_path(@annotation) %> |
<%= link_to 'Back', annotations_path %>

app/views/annotations/show_user_annotations.html.erb
<!-- TODO: show Language instead of language code-->

<h1>All the annotations done by <%=  @user.user_name %></h1>

<table class="table table-striped">
  <tr>
    <th>No.</th>
    <th>Language</th>
    <th>Selected text</th>
    <th>Translation</th>
    <th>Url of the article</th>
  </tr>


<% @annotations.each_with_index do |annotation, index| %>
  <tr>
    <td><%=index+1 %></td>
    <td><%= annotation.lang %></td>
    <td><%= annotation.selected_text %></td>
    <td><%= annotation.translation %></td>
    <!-- TODO: show link-->
    <!--<td><%= annotation.article.nil? ? '': annotation.article.url%></td>-->
    <td><a href='<%= annotation.article.url%>'><%= annotation.article.url%></a></td>
  </tr>
<% end %>
</table>

app/views/annotations/show_user_urls.html.erb
<h1>All the articles annotated  by <%=  @user.user_name %></h1>

<table class="table table-striped">
  <tr>
    <th>No. </th>
    <th>Article</th>
    <th>Language</th>
    <th>Publication Date</th>
  </tr>

  <% @articles.each_with_index do |article, index| %>
    <tr>
      <td><%=index+1 %></td>
      <td><a href='<%=article.url %>'><%= article.title %></a></td>
      <td><%= article.lang %></td>
      <td><%= article.publication_date %></td>
    </tr>
  <% end %>
</table>

<br />